[env:arduino_nano_esp32]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.39/platform-espressif32.zip
board = arduino_nano_esp32
framework = arduino
upload_protocol = esptool
lib_extra_dirs = ../common
monitor_speed = 115200
lib_deps =
    bblanchon/ArduinoJson@7.4.3
    h2zero/NimBLE-Arduino@2.5.0
build_flags =
    -DCORE_DEBUG_LEVEL=1

[env:seeed_xiao_esp32c3]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.39/platform-espressif32.zip
board = seeed_xiao_esp32c3
framework = arduino
board_build.partitions = ota_nofs_4MB.csv
lib_extra_dirs = ../common
monitor_speed = 115200
lib_deps =
    bblanchon/ArduinoJson@7.4.3
    h2zero/NimBLE-Arduino@2.5.0
build_flags =
    -DCORE_DEBUG_LEVEL=1
