[env:arduino_nano_esp32]
platform = espressif32@55.3.39
board = arduino_nano_esp32
framework = arduino
board_build.partitions = app3M_fat9M_fact512k_16MB.csv
lib_extra_dirs = ../common
monitor_speed = 115200
lib_deps =
    bblanchon/ArduinoJson@^7.4.3
    h2zero/NimBLE-Arduino@2.5.0
    miguelbalboa/MFRC522@^1.4.12
build_flags =
    -DCORE_DEBUG_LEVEL=1
    -DVALIDATOR_ALLOW_LEGACY_EQUIPMENT=0
